version: '2'

services:
  front:
    restart: always
    build: "_front"
    ports:
      - "8888:8080"

  api:
    restart: always
    build: "api"
    environment:
      - RUNMODE=api
      - DEBUG
      - DEV
      - HTTP_PORT
    volumes:
      - "./api/data/src:/data/src"

  worker:
    restart: always
    build: "api"
    environment:
      - RUNMODE=worker
    volumes:
      - "./api/data/src:/data/src"

  www:
    restart: always
    build: "www"
    volumes:
      - "./www/data:/data"

  cache:
    restart: always
    image: "redis:3.2-alpine"
    volumes:
      - "./data/redis:/data"

  mq:
    restart: always
    image: "rabbitmq:3.6.6-management"

  db:
    restart: always
    image: "postgres:9.6.1-alpine"
    volumes:
      - "./data/db/data:/var/lib/postgresql/data"

