#!/usr/bin/with-contenv sh

[[ "${RUNMODE}" == "api" ]] || ( /usr/bin/s6-stopdisable api-websocket-receiver && exit 0 )

cd /data/src
exec s6-setuidgid django /usr/bin/daphne -p 5001 server_apps:websocket
