#!/usr/bin/with-contenv sh

[[ "${RUNMODE}" == "worker" ]] || ( /usr/bin/s6-stopdisable celery-worker && exit 0 )

cd /data/src
exec s6-setuidgid django /usr/bin/celery worker -b amqp://guest:guest@mq:5672// -B -E -A lib.celery_instance.app -s /data/celery/celerybeat-schedule --autoscale=2,12;
